server:
  port: 8080  # Application running port

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tooldb
    username: root
    password: lion

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  # Redis 
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

  # Mail configuration )
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: 587
    username: ${MAIL_USERNAME:test@gmail.com}
    password: ${MAIL_PASSWORD:testpassword}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # File upload config 
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# JWT config 
jwt:
  secret: ${JWT_SECRET:mysecretkey}
  expiration: 86400000

  springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true